classification:
  Model1:
    conv_hidden_dim: 512
    dr_rate: 30
    feature_dim: 812
    num_layer: 3
    out_din: 115
  Model2:
    conv_hidden_dim: 512
    dr_rate: 30
    feature_dim: 512
    out_dim: 1
  Model3:
    conv_hidden_dim: 512
    dr_rate: 30
    feature_dim: 512
    out_dim: 115
  Model4:
    Nframe: 256
    conv_hidden_dim: 256
    dr_rate: 50
    feature_dim: 768
    out_dim: 115
